### ISSUE TITLE
create registry error

### ISSUE THREAD

**Issue by bengrissinger** [containerish/OpenRegistry#71]
got logged in fine (Once I read the blog material :)  \

docker login beta.openregistry.dev
Authenticating with existing credentials...
Login Succeeded

pulled an existing image fine
docker pull beta.openregistry.dev/gunjanwalecha/nginx
Using default tag: latest
latest: Pulling from gunjanwalecha/nginx
b380bbd43752: Pull complete 
fca7e12d1754: Pull complete 
745ab57616cb: Pull complete 
a4723e260b6f: Pull complete 
1c84ebdff681: Pull complete 
858292fd2e56: Pull complete 
Digest: sha256:df4aa677e738abf4891ffb24f5723a84f1dfd87a36a33d742c2432e5f916f8d6
Status: Downloaded newer image for beta.openregistry.dev/gunjanwalecha/nginx:latest
beta.openregistry.dev/gunjanwalecha/nginx:latest

**tagged an image and tried to push, it fails** (I didnt see where I can create a public or private registry, figure it was open as default)

docker tag redis:latest beta.openregistry.dev/grissinb/redis:latest

docker push beta.openregistry.dev/grissinb/redis:latest
The push refers to repository [beta.openregistry.dev/grissinb/redis]
e32a54e9cf7b: Preparing 
9cf6f7d59322: Preparing 
1d07bac5c7c7: Preparing 
cf2aefb51919: Preparing 
a6b7270e6c20: Preparing 
14a1ca976738: Waiting 
unauthorized: authentication required

**Comment by guacamole** [comment]
Hi @bengrissinger ,
First of all, thank you for using OpenRegistry!
For the initial feature, we only have public images and pull operations do not require authentication. On the other hand, Pushing an image does require for you to be authenticated.

What decides you're authorised to push an image?
When you received an invitation email from OpenRegistry, you mush have received :

username
email and
password

Email id used to login through our webapp only. Now, username is of importance here.
When tagging your image, use the same username as that of from the email(this will tell OpenRegistry that the user logged in and the one pushing the image are same, thus authorised 🎉 ).
Please try to tag your image like following and try to push the image:

`docker tag redis:latest beta.openregistry.dev/<your username>/redis:latest`

We're working on making the blog better and more conveying. Please let us know if it works or even otherwise and we'd love to help you with it.

**Comment by bengrissinger** [comment]
awesome, works great, I switched to the username that was sent to my signup email, and it worked great

**Comment by bengrissinger** [comment]
cant wait for this project to get to prod status.  I'll be the first in line to use.
